---
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: check-exif
jobs:
  privacy-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install exiftool
        run: sudo apt-get install -y libimage-exiftool-perl
      - name: verify no privacy metadata in build output
        run: bash .common/check-exif.sh ./
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: install tools
        run: |
          pip install platformio==6.1.19
      - name: build examples
        run: make -C .common ci
